### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by ventilator** [marove2000/referenceCards#1]
Consider consistent lower case in english (unsure about this since adafruit also makes with wrong?)
Consider reverse point 2's order: 1) Keep heating 2) add solder
![image](https://user-images.githubusercontent.com/4276067/100462255-4723fd00-30ca-11eb-81ae-b85c4456b81f.png)

Consider rewording "marks" and arrow - since the arrow is located on the positive side, maybe better. "Arrow points to negative side"

Consider consitent headline style (" " vs ":"): SMD Soldering vs SMD:Directions

![image](https://user-images.githubusercontent.com/4276067/100462461-9a964b00-30ca-11eb-9b46-4e33c0356e7f.png)

Typo "sodering"

![image](https://user-images.githubusercontent.com/4276067/100462712-f365e380-30ca-11eb-9786-322de8781feb.png)

**Comment by marove2000** [comment]
Thanks for the feedback. Fixed all issues.
